# Generated by Django 4.2.5 on 2023-09-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='../static/male_avator.png', upload_to='ProfilePhoto/%Y/%m/%d'),
        ),
    ]
