# Generated by Django 4.2.5 on 2023-09-28 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_alter_bookinfo_author_alter_bookinfo_category_and_more'),
        ('account', '0004_alter_userprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadbooks',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_books', to='bookstore.bookinfo'),
        ),
    ]
