# Generated by Django 3.2.19 on 2023-09-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_info',
            name='book_file',
            field=models.FileField(max_length=255, null=True, upload_to='booksFile/% Y/% m/% d'),
        ),
        migrations.AlterField(
            model_name='book_info',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='booksCover/% Y/% m/% d'),
        ),
    ]
