# Generated by Django 4.2.5 on 2023-09-20 21:27

import bookstore.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20230920_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='book_file',
            field=models.FileField(max_length=255, null=True, upload_to=bookstore.models.set_pdf_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='book_info',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=bookstore.models.set_cover_filename),
        ),
    ]
