# Generated by Django 4.2.5 on 2023-09-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_remove_book_info_book_file_remove_book_info_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='Pages',
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='category',
            field=models.CharField(choices=[('python', 'Python'), ('Kali', 'Kali'), ('Linux command', 'Linux command'), ('Networking', 'Networking'), ('Ethical hacking', 'Ethical hacking'), ('Django', 'Django'), ('Android', 'Android'), ('Kotlin', 'Kotlin'), ('Handout', 'Handout')], max_length=255),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='pages',
            field=models.IntegerField(null=True),
        ),
    ]
