# Generated by Django 4.2.5 on 2023-09-23 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_remove_bookinfo_pages_alter_bookinfo_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique_for_date=models.DateTimeField(auto_now_add=True)),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
