# Generated by Django 4.2.5 on 2023-09-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_bookinfo_slug_bookinfo_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='category',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('Kali', 'Kali'), ('Linux command', 'Linux command'), ('Networking', 'Networking'), ('Ethical hacking', 'Ethical hacking'), ('Django', 'Django'), ('Android', 'Android'), ('Kotlin', 'Kotlin'), ('Handout', 'Handout')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='published_year',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
