# Generated by Django 4.2.5 on 2023-10-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_bookinfo_file_type_alter_bookinfo_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='category',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('Kali linux', 'Kali linux'), ('Linux command', 'Linux command'), ('Networking', 'Networking'), ('Ethical hacking', 'Ethical hacking'), ('Django', 'Django'), ('Android', 'Android'), ('Kotlin', 'Kotlin'), ('Handout', 'Handout'), ('Javascript', 'javascript')], max_length=255, null=True),
        ),
    ]
